### ISSUE TITLE
fix dependent-bot warning 

### ISSUE THREAD

**Issue by stechu** [Manta-Network/manta-signer#24]
https://github.com/Manta-Network/manta-signer/security/dependabot

**Comment by bhgomes** [comment]
If we add a `dependabot.yml` file to `.github` directory:

```yaml
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "daily"
```
